include: package:flutter_lints/flutter.yaml
# include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: 
    - [build/**]
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - lib/*.config.dart
    - lib/**/*.freezed.dart
    - lib/**/*.reflectable.dart

    - packages/*/

  errors:
    invalid_annotation_target: ignore
    sort_child_properties_last: ignore
    use_build_context_synchronously: ignore
    library_private_types_in_public_api: ignore

linter:
  rules:
    - camel_case_types
    - prefer_const_declarations