name: mvvm_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # CORE
  dartz: ^0.10.1
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  kt_dart: ^0.10.0
  rxdart: ^0.27.5
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # LINT
  # very_good_analysis: ^3.1.0
  flutter_lints: ^2.0.1
  lint: ^1.10.0
  analyzer: ^4.7.0
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  injectable_generator: ^1.5.4
  mockito: any

flutter:
  uses-material-design: true